### ISSUE TITLE
Can you make it customize the left and right softkeys too?

### ISSUE THREAD

**Issue by LL-BB** [biden2020prez/CustomLG-Hotkeys#1]
Hi. It's L-B from the apps4flip forums. Works great thank you so much.

Can you make it customize the left and right softkeys too? so I can open my own messaging app with the right softkey (top right key) instead of the built in messaging app?

**Comment by SZRabinowitz** [comment]
Unfortunately that cannot be controlled with ADB. Using [CoolHome](https://github.com/biden2020prez/CoolHome) it is possible but would requiring modifying Smali directly. It's been a log time since I looked at that so I don't rememeber where the code is.

**Comment by LL-BB** [comment]
okay thanks so much
